spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        show_sql: false # SQL 콘솔 출력
        jdbc:
          batch_size: 100
        generate_statistics: true
    database-platform: org.hibernate.dialect.MySQL57Dialect # MySQL 5.7의 방언

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: root
    password: qudrnr132!

logging:
  level:
    ROOT: INFO
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.type.descriptor.sql: trace

security:
  jwt:
    token:
      secret-key: atdd-secret-key
      expire-length: 3600000

github:
  base-url: https://github.com/
  client:
    id: client-id
    secret: github-client-secret

payment-webhook:
  base-url: https://payment-webhook.com/ # TODO 추후 외부 PG 연동 후 수정
  get-access-token-url: /users/getToken
  get-payment-info-url: /payments/%s/balance
  client:
    api-key: api-key
    api-secret-key: api-secret-key