spring:
  profiles:
    active: dev # defualt
    group:
      dev:
        - common
        - dev

---
spring:
  config:
    activate:
      on-profile: "common"

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    ROOT: INFO
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.type.descriptor.sql: trace
---