SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE MEMBER RESTART IDENTITY;
TRUNCATE TABLE MEMBER_SECURITY RESTART IDENTITY;
TRUNCATE TABLE ADDRESS RESTART IDENTITY;
TRUNCATE TABLE ADMIN RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;